Closes #136
ekzhang/setwithfriends pull request #144
Opened 2022-11-08 18:57 UTC by vEnhance

is this how you add a newline in JSX i have no idea lol

2023-03-14 02:20 UTC, HiddeKoerts requested changes
I like the functionality a lot, and it works beautifully. 

I'm personally not a fan of including the keyboard shortcut in the button label, it makes it visually very cluttered. I'd be in favor of removing it, and adding a paragraph on the 'Help' page (in the Layout and Controls section). Especially because the key combinations you have chosen (I don't know any better ones) might interact with browsers as well.

Also, would it be possible to have another hotkey for the 'Play again' button at the end of the game? That would be very helpful for someone to fully interact with the website by keyboard only.

2024-12-29 05:46 UTC, vEnhance commented
saw that development on this repo is starting back up again, so i'll try to bring this PR up to date at some point when i'm back in boston in january (so removing the keyboard shortcut and adding a "play again" hotkey).

2025-01-05 17:06 UTC, vEnhance commented
Made the promised changes (although I'm not in boston yet: flying out today :grin: ).

2025-01-25 18:44 UTC, vEnhance commented
Just want to check if there's anything else needed for this or #145, no rush.
Have a nice weekend!

2025-01-27 20:26 UTC, ekzhang approved these changes

2025-01-27 20:26 UTC, merged

2025-01-27 20:26 UTC, ekzhang commented
Thank you!