Msg tab notification
ekzhang/setwithfriends pull request #85
Opened 2021-02-04 12:35 UTC by Hanaffi

https://github.com/ekzhang/setwithfriends/issues/84

2021-02-22 22:31 UTC, ekzhang requested changes

2021-02-22 22:31 UTC, ekzhang commented on src/components/Chat.js
> +/* eslint-disable eqeqeq */
Please don't disable lints without a good reason. Instead, you can use the `===` and `!==` operators, as ESLint suggests.

2021-02-22 22:31 UTC, ekzhang commented on src/components/Chat.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
This isn't correct; the `exhaustive-deps` lint should be satisfied for soundness. Otherwise, you could end up with stale data. See this [Stack Overflow question](https://stackoverflow.com/questions/58866796/understanding-the-react-hooks-exhaustive-deps-lint-rule).

2021-02-22 22:31 UTC, ekzhang commented on src/components/Chat.js
> +    if (msgCounter) document.title = `Set with friends - (${msgCounter})`;
This makes sense, however, it should be capitalized `"Set with Friends"`.

2021-02-22 22:31 UTC, ekzhang commented on src/components/Chat.js
> +  const [previousMessages, setPreviousMessages] = useState({});
This variable is unused. Rather than disabling the lint, you could also just remove the variable entirely.

2021-03-16 02:46 UTC, ekzhang commented
@Hanaffi Any updates on this?

2021-03-16 20:30 UTC, Hanaffi commented
@ekzhang  Excuse me, I have been busy with final exams. 
I will finish on Thursday, After that I will work on these two PRs.

2021-03-25 19:35 UTC, closed without merging